services:
  api:
    build: .
    container_name: fastapi
    ports:
      - "8000:8000"
    restart: always
  n8n:
    image: n8nio/n8n
    container_name: n8n
    ports:
      - "5678:5678"
    environment:
      - GENERIC_TIMEZONE=Asia/Jakarta
    depends_on:
      - api
    restart: always
    volumes:
    - ./n8n:/home/node/.n8n
  